version: '3'
services:

  mongo:
    image: mongo:3.6
    restart: always
    command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./cache/mongodata:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092"
      - "9092-9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:3:3,response:3:3,request:3:3,offer:3:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cache/kafka-tmp:/tmp/

  # docker-compose run postgres bash
  # psql -h postgres -d mydbname -U root
  postgres:
    image: postgres:12.2
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: mydbname
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
     - ./cache/postgres:/var/lib/postgresql/data

  # mkdir -p cache/pgadmin
  # chown -R 5050:5050 cache/pgadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
     - "8082:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./cache/pgadmin:/var/lib/pgadmin

  # root // rootpassword
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
      #ARANGO_NO_AUTH: 1
    ports:
      - 8529:8529
    volumes:
      - ./cache/arangodb_data_container:/var/lib/arangodb3
      - ./cache/arangodb_apps_data_container:/var/lib/arangodb3-apps
