version: '3'
services:

  mongo:
    image: mongo:3.6
    restart: always
    command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./cache/mongodata:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.1
    ports:
      - "9092"
      - "9092-9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:3:3,response:3:3,request:3:3,offer:3:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cache/kafka-tmp:/tmp/

  # docker compose run postgres bash
  # psql -h postgres -d mydbname -U root
  postgres:
    image: postgres:12.2
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: mydbname
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
     - ./cache/postgres:/var/lib/postgresql/data

  # mkdir -p cache/pgadmin
  # chown -R 5050:5050 cache/pgadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
     - "8082:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./cache/pgadmin:/var/lib/pgadmin

  # root // rootpassword
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
      #ARANGO_NO_AUTH: 1
    ports:
      - 8529:8529
    volumes:
      - ./cache/arangodb_data_container:/var/lib/arangodb3
      - ./cache/arangodb_apps_data_container:/var/lib/arangodb3-apps

  couchbase:
    image: couchbase:latest
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - ./cache/couchbase:/opt/couchbase/var

  # mkdir -p cache/elasticsearch
  # chown -R 1000:1000 cache/elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./cache/elasticsearch:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  # mkdir -p cache/elasticsearch6
  # chown -R 1000:1000 cache/elasticsearch6
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.18
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./cache/elasticsearch6:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.13.3
    ports:
      - 5601:5601
    volumes:
    - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml

  # docker compose run redis bash
  # redis-cli -h 192.168.1.2 # local machine ip
  redis:
    image: redis:6.2.4
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./cache/redis:/data

  # docker compose run elasticsearch-dump bash
  # mkdir -p cache/elasticsearch-dump/
  elasticsearch-dump:
    image: elasticdump/elasticsearch-dump:latest
    volumes:
      - ./cache/elasticsearch-dump:/data

  # docker compose run kafkactl consume topic
  # docker compose run --entrypoint /bin/bash kafkactl
  kafkactl:
    image: deviceinsight/kafkactl:v1.20.0
    volumes:
      - ~/.config/kafkactl/config.yml:/etc/kafkactl/config.yml
